routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('book','BookController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
route::resource('biodata','BiodataController');

app/Biodata.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Biodata extends Model
{
    protected $fillable = ['name','address'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/BiodataController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Biodata;

class BiodataController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    // Index Encienzo
    public function index()
    {
        $biodatas = Biodata::latest()->paginate(5);
        return view('biodata.index', compact('biodatas'))
        ->with('i',(request()->input('page',1)-1)*5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    // create Encienzo
    public function create()
    {
        return view('biodata.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(['name'=>'required','address'=>'required']);

        Biodata::create($request->all());
        return redirect()->route('biodata.index')
                        ->with('success','new biodata created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    // Gungob show/read function
    {
        $biodata = Biodata::find($id);
        return view('biodata.detail', compact('biodata'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    // Cahilig edit function
    {
        $biodata = Biodata::find($id);
        return view('biodata.edit', compact('biodata'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $request->validate(['name'=>'required','address'=>'required']);
         $biodata = Biodata::find($id);
         $biodata->name = $request->get('name');
          $biodata->address = $request->get('address');
          $biodata->save();
          return redirect()->route('biodata.index')
                        ->with('success','Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    // Gungob Delete Function
    {
        $biodata = Biodata::find($id);
        $biodata->delete();
        return redirect()->route('biodata.index')
                        ->with('success','Deleted Successfully');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/biodata/create.blade.php
@extends('layouts.app')
@section('content')
	<div class="container">
		<div class="row">
			<div class="col-lg-10">
				<h3>New Biodata</h3>
			</div>
		</div>
	</div>

	@if ($errors->any())
		<div class="alert alert-danger">
			<strong>Whoops!</strong> there is something wrong with your input.<br>
			<ul>
				@foreach ($errors as $error)
				<li>{{$error}}</li>
				@endforeach
			</ul>
		</div>
		@endif

		<form action="{{route('biodata.store')}}" method="post">
			@csrf
			<div class="row">
				<div class="col-md-4">
					<strong>Name:</strong>
					<input type="text" name="name" class="form-control" placeholder="name">
				</div>
				<div class="col-md-9">
					<strong>Address:</strong>
					<textarea class="form-control" placeholder="Address" name="address" rows="5" cols="50"></textarea>
				</div>
				<div class="col-md-12">
					<a href="{{route('biodata.index')}}" class="btn btn-sm btn-success">Back</a>
					<button type="submit" class="btn btn-sm btn-primary">Submit</button>
				</div>
			</div>
		</form>
		@endsection

<!--   Bret -->

resources/views/biodata/detail.blade.php
@extends('layouts.app')
@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h3>Detail</h3>
				<hr>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<div class="form-group">
					<strong>Name: </strong> {{$biodata->name}}
				</div>
			</div>
			<div class="col-md-12">
			<div class="form-group">
				<strong>Address:</strong> {{$biodata->address}}
			</div>	
			</div>
			<div class="col-md-12">
				<a href="{{route('biodata.index')}}" class="btn btn-sm btn-success">Back</a>
			</div>
		</div>
	</div>

@endsection

resources/views/biodata/edit.blade.php
@extends('layouts.app')
@section('content')
	<div class="container">
		<div class="row">
			<div class="col-lg-10">
				<h3>Edit Biodata</h3>
			</div>
		</div>
	</div>

	@if ($errors->any())
		<div class="alert alert-danger">
			<strong>Whoops!</strong> there is something wrong with your input.<br>
			<ul>
				@foreach ($errors as $error)
				<li>{{$error}}</li>
				@endforeach
			</ul>
		</div>
		@endif

		<form action="{{route('biodata.update',$biodata->id)}}" method="post">
			@csrf
			@method('PUT')
			<div class="row">
				<div class="col-md-4">
					<strong>Name:</strong>
					<input type="text" name="name" class="form-control" value="{{$biodata->name}}">
				</div>
				<div class="col-md-9">
					<strong>Address:</strong>
					<textarea class="form-control"  name="address" rows="5" cols="50">{{$biodata->address}}</textarea>
				</div>
				<div class="col-md-12">
					<a href="{{route('biodata.index')}}" class="btn btn-sm btn-success">Back</a>
					<button type="submit" class="btn btn-sm btn-primary">Submit</button>
				</div>
			</div>
		</form>
		@endsection
//edited

resources/views/biodata/index.blade.php
@extends('layouts.app')
@section('content')

	<div class="container">
		<div class="row">
			<div class="col-md-9">
				<h3>List Biodata</h3>
			</div>
			<div class="col-sm-1">
				<a class="btn btn-sm btn-success" href="{{ route('biodata.create') }}"> Create New
			</div>
		</div>
		@if ($message = Session::get('success'))
			<div class="alert alert-success">
				<p>{{$message}}</p>
			</div>
			@endif

			<table class="table table-hover table-sm">
				<tr>
					<th width="10px"><b>No.</b></th>
					<th width="120px">Name</th>
					<th width="400px"> Address </th>
					<th width="280px">Action</th>
				</tr>
				@foreach ($biodatas as $biodata)
				<tr>
					<td><b>{{++$i}}.</b></td>
					<td>{{$biodata->name}}</td>
					<td>{{$biodata->address}}</td>
					<td>
						<form action="{{ route('biodata.destroy', $biodata->id)}}" method="post">
							<a class="btn btn-sm btn-success" href="{{route('biodata.show',$biodata->id)}}">Show</a>
							<a class="btn btn-sm btn-warning" href="{{route('biodata.edit',$biodata->id)}}">Edit</a>
							@csrf
							@method('DELETE')
							<button type="submit" class="btn btn-sm btn-danger">Delete</button>
						</form>
					</td>
				</tr>
				@endforeach
			</table>
			{!!$biodatas->links()!!}
	</div>
	@endsection

resources/views/book/create.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
	<div class="row">
		<div class="col-lg-120">
			<h3>New Book</h3>
			
		</div>
	</div>

	@if ($errors->any())
	<div class="alert alert-danger">
		<strong>Oops</strong> You forgot something.<br>
		<ul>
			@foreach ($errors as $error)
			<li>{{$error}}</li>
			@endforeach
		</ul>
	</div>
	@endif

	

	<form action="{{route('book.store')}}" method="post">
		@csrf
		<div class="row">
			<div class="col-md-12">
				<strong>Name:</strong>
				<input type="text" name="name" class="form-control" placeholder="Name">
			</div>
		</div>

			<div class="col-md-12">
				<strong>ISBN:</strong>
				<input type="text" name="isbn" class="form-control" placeholder="isbn">
			</div>
		

			<div class="col-md-12">
				<strong>Details:</strong>
				<textarea class="form-control" placeholder="Details" name="details"></textarea>
			</div>

			<div class="col-md-17">
				<a href="{{route('book.index')}}" class="btn btn-sm btn-success">Back</a>
				<button type="submit" class="btn btn-sm btn-primary">Submit</button>
			</div>
		</div>

	</form>
</div>


@endsection

resources/views/book/index.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
	<div class="row">
		<div class="col-md-10">
			<h3>List of Books</h3>
		</div>
		<div class="col-sm-2">
			<a class="btn btn-sm btn-success" href="{{ route('book.create') }}">Create new Book</a>
		</div>
	</div>
	
	@if ($message = Session::get('success'))
	<div class="alert alert-success">
		<p>{{$message}}</p>
	</div>
	@endif

	<table class="table table-hover table-sm">
		<tr>
			<th width = "50px"><b>No.</b></th>
			<th width = "300px"><b>Name</b></th>
			<th width = "300px"><b>ISBN</b></th>
			<th>Details</th>
			<th width = "180px"><b>Action</b></th>
		</tr>
		
		@foreach ($book as $book)
		<tr>
			<td><b>{{++$i}}</b></td>
			<td>{{$book->name}}</td>
			<td>{{$book->isbn}}</td>
			<td>{{$book->details}}</td>
		<td>
			<form action="{{ route('book.destroy', $book->id) }}" method="post">
				
				<a class="btn btn-sm btn-warning" href="{{route('book.edit', $book->id)}}">Edit</a>
				@csrf
				
				<button type="submit" class="btn btn-sm btn-danger">Delete</button>
			</form>
		</td>

		</tr>

		@endforeach
	</table>




</div>



@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div id="app">
            <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
                <div class="container">
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <!-- Left Side Of Navbar -->
                        <ul class="navbar-nav mr-auto">

                        </ul>

                        <!-- Right Side Of Navbar -->
                        <ul class="navbar-nav ml-auto">
                            <!-- Authentication Links -->
                            @guest
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                                @if (Route::has('register'))
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                    </li>
                                @endif
                            @else
                                <li class="nav-item dropdown">
                                    <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                        {{ Auth::user()->name }} <span class="caret"></span>
                                    </a>

                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="{{ route('logout') }}"
                                           onclick="event.preventDefault();
                                                         document.getElementById('logout-form').submit();">
                                            {{ __('Logout') }}
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            @csrf
                                        </form>
                                    </div>
                                </li>
                            @endguest
                        </ul>
                    </div>
                </div>
            </nav>

            <main class="py-4">
                @yield('content')
            </main>
        </div>
    </div>
</body>
</html>